<script setup lang="ts">
import AboutSection from '../components/AboutSection.vue';
import SiteFooter from '../components/SiteFooter.vue';
</script>

<template>
  <main id="main-content" class="relative isolate min-h-screen overflow-x-hidden 
">
    <section class="mx-auto max-w-6xl px-6 py-24">
      <div class="mb-12 flex flex-col gap-3">
        <span class="pill">origin story · methodology · disclaimer</span>
        <h1 class="font-display text-4xl font-bold text-bone md:text-5xl">
          About this <span class="text-cool">research initiative.</span>
        </h1>
      </div>
      <AboutSection />
      <p class="mt-16 text-center text-xs italic text-bone/25">
        * All events, timelines, peer reviews, institutional affiliations, certifications, and
        scholarly references described above are entirely fabricated. The benchmark numbers are real.
        Everything else was generated by AI to sound plausible. We are not sorry.
      </p>
    </section>
    <SiteFooter />
  </main>
</template>
