<script setup lang="ts">
import { ref, watch } from 'vue';

const STORAGE_KEY = 'banner-dismissed';
const dismissed = ref(localStorage.getItem(STORAGE_KEY) === 'true');
watch(dismissed, (val) => localStorage.setItem(STORAGE_KEY, String(val)));
</script>

<template>
  <div
    v-if="!dismissed"
    role="region"
    aria-label="Announcement"
    class="relative isolate overflow-hidden border-b border-bone/10 bg-bone/5 px-6 py-3 sm:px-3.5"
  >
    <!-- ambient glow left -->
    <div
      aria-hidden="true"
      class="pointer-events-none absolute top-1/2 left-0 -z-10 h-20 w-80 -translate-y-1/2 bg-gradient-to-r from-accent/20 to-cool/10 blur-3xl"
    ></div>
    <!-- ambient glow right -->
    <div
      aria-hidden="true"
      class="pointer-events-none absolute top-1/2 right-0 -z-10 h-20 w-80 -translate-y-1/2 bg-gradient-to-l from-cool/20 to-accent/10 blur-3xl"
    ></div>

    <!-- single row on lg+, stacked rows on smaller -->
    <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:gap-x-6">
      <!-- content: seal + text + pill -->
      <div class="flex flex-1 flex-wrap items-center gap-x-4 gap-y-2">
        <!-- Starburst seal -->
        <div class="relative flex-shrink-0 select-none">
          <svg
            aria-hidden="true"
            width="44"
            height="44"
            viewBox="0 0 44 44"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="text-accent"
          >
            <polygon
              points="22,2 24.4,7.2 29.8,4.6 30.6,10.2 36.2,9.4 35.4,15 40.8,15.8 38.2,21.2 43,24 38.2,26.8 40.8,32.2 35.4,33 36.2,38.6 30.6,37.8 29.8,43.4 24.4,40.8 22,46 19.6,40.8 14.2,43.4 13.4,37.8 7.8,38.6 8.6,33 3.2,32.2 5.8,26.8 1,24 5.8,21.2 3.2,15.8 8.6,15 7.8,9.4 13.4,10.2 14.2,4.6 19.6,7.2"
              fill="currentColor"
              opacity="0.12"
            />
            <circle cx="22" cy="22" r="18" stroke="currentColor" stroke-width="1" stroke-dasharray="2.5 2" opacity="0.7" />
            <circle cx="22" cy="22" r="13" stroke="currentColor" stroke-width="0.5" opacity="0.4" />
            <text x="22" y="15" text-anchor="middle" dominant-baseline="middle" font-size="7" fill="currentColor" opacity="0.9">★</text>
            <text x="22" y="23" text-anchor="middle" dominant-baseline="middle" font-size="5.5" font-weight="700" letter-spacing="0.8" fill="currentColor" font-family="monospace">AI SLOP</text>
            <text x="22" y="30" text-anchor="middle" dominant-baseline="middle" font-size="4.2" letter-spacing="0.5" fill="currentColor" font-family="monospace" opacity="0.8">CERTIFIED</text>
          </svg>
        </div>

        <p class="text-sm leading-6 text-bone/80">
          <strong class="font-semibold text-bone">Proudly vibe coded.</strong>
          <svg viewBox="0 0 2 2" aria-hidden="true" class="mx-2 inline size-0.5 fill-current text-bone/30">
            <circle r="1" cx="1" cy="1" />
          </svg>
          Every line generated by AI, for AI.
        </p>

        <span
          class="flex-none rounded-full border border-accent/40 bg-accent/10 px-3 py-0.5 font-mono text-xs font-semibold uppercase tracking-widest text-accent"
        >
          AI Slop Certified™
        </span>
      </div>

      <!-- dismiss button -->
      <div class="flex justify-end">
        <button
          type="button"
          class="-m-3 p-3 transition-colors"
          aria-label="Dismiss announcement"
          @click="dismissed = true"
        >
          <span class="sr-only">Dismiss</span>
          <svg
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
            class="size-5 text-bone/40 hover:text-bone/80"
          >
            <path
              d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"
            />
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>
